# USER ROUTES

### Registrar usuario
POST http://localhost:5000/auth/register/
Content-Type: application/json

{
  "email": "albertus1291@gmail.com",
  "password": "1234"
}


### Logear usuario
POST http://localhost:5000/authlogin/
Content-Type: application/json

{
  "email": "albertus1291@gmail.com",
  "password": "1234"
}

# LINK ROUTES

### Crear un nuevo enlace acortado SIN usuario registrado
POST http://localhost:5000/links/
Content-Type: application/json

{
  "originalUrl": "https://albertcastroportfolio.netlify.app/",
  "shortUrl": "portfolio"
}

### Crear un nuevo enlace acortado CON usuario registrado
POST http://localhost:5000/links/
Content-Type: application/json

{
  "originalUrl": "https://github.com/BeruzDev",
  "shortUrl": "github",
  "userId": "c472618d-0310-4a93-b282-222f9643cfa8"
}

### Recuperar links del usuario
GET http://localhost:5000/links/my-links
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNDcyNjE4ZC0wMzEwLTRhOTMtYjI4Mi0yMjJmOTY0M2NmYTgiLCJpYXQiOjE3NDMwOTg0MTUsImV4cCI6MTc0MzEwMjAxNX0.XcOyuM5tH7UNKhMfMMDGxe8lxlkd4vtRsBbm0Y6Pm-k

{
  "userId": "c472618d-0310-4a93-b282-222f9643cfa8"
}

### Modificar el endpoint
PUT http://localhost:5000/links/6a3461e5-83c4-428d-98fa-7863b074cbb6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNDcyNjE4ZC0wMzEwLTRhOTMtYjI4Mi0yMjJmOTY0M2NmYTgiLCJpYXQiOjE3NDMwOTg0MTUsImV4cCI6MTc0MzEwMjAxNX0.XcOyuM5tH7UNKhMfMMDGxe8lxlkd4vtRsBbm0Y6Pm-k

{
  "linkId": "6a3461e5-83c4-428d-98fa-7863b074cbb6",
  "newShortUrl": "github"
}

### Eliminar link
DELETE http://localhost:5000/links/6a3461e5-83c4-428d-98fa-7863b074cbb6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNDcyNjE4ZC0wMzEwLTRhOTMtYjI4Mi0yMjJmOTY0M2NmYTgiLCJpYXQiOjE3NDMwOTg0MTUsImV4cCI6MTc0MzEwMjAxNX0.XcOyuM5tH7UNKhMfMMDGxe8lxlkd4vtRsBbm0Y6Pm-k

### Redireccion con el enlace proporcionado
GET http://localhost:5000/github