# USER ROUTES

### Registrar usuario
POST http://localhost:5000/auth/register/
Content-Type: application/json

{
  "email": "albertus1291@gmail.com",
  "password": "12345678910"
}


### Logear usuario
POST http://localhost:5000/auth/login/
Content-Type: application/json

{
  "email": "albertus1291@gmail.com",
  "password": "12345678910"
}

# LINK ROUTES

### Crear un nuevo enlace acortado SIN usuario registrado
POST http://localhost:5000/links/
Content-Type: application/json

{
  "originalUrl": "www.testing.com",
  "shortUrl": "prueba"
}

### Crear un nuevo enlace acortado CON usuario registrado
POST http://localhost:5000/links/
Content-Type: application/json

{
  "originalUrl": "https://github.com/BeruzDev",
  "shortUrl": "github",
  "userId": "e048d056-3f3e-4ba8-a13d-0570367d9123"
}

### Recuperar links del usuario
GET http://localhost:5000/links/my-links
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDQ4ZDA1Ni0zZjNlLTRiYTgtYTEzZC0wNTcwMzY3ZDkxMjMiLCJpYXQiOjE3NDQyMDAzOTksImV4cCI6MTc0NDIwMzk5OX0.UHXb0LEJljwHv0q8Rhaba3wTiNIYZv_olzqg8C9UZjQ

{
  "userId": "e048d056-3f3e-4ba8-a13d-0570367d9123"
}

### Modificar el endpoint
PUT http://localhost:5000/links/92a5693b-99aa-4672-8089-39192310d1e4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDQ4ZDA1Ni0zZjNlLTRiYTgtYTEzZC0wNTcwMzY3ZDkxMjMiLCJpYXQiOjE3NDQyMDAzOTksImV4cCI6MTc0NDIwMzk5OX0.UHXb0LEJljwHv0q8Rhaba3wTiNIYZv_olzqg8C9UZjQ

{
  "linkId": "92a5693b-99aa-4672-8089-39192310d1e4",
  "newShortUrl": "githubBeruzDev"
}

### Eliminar link
DELETE http://localhost:5000/links/92a5693b-99aa-4672-8089-39192310d1e4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDQ4ZDA1Ni0zZjNlLTRiYTgtYTEzZC0wNTcwMzY3ZDkxMjMiLCJpYXQiOjE3NDQyMDAzOTksImV4cCI6MTc0NDIwMzk5OX0.UHXb0LEJljwHv0q8Rhaba3wTiNIYZv_olzqg8C9UZjQ

### Redireccion con el enlace proporcionado
GET http://localhost:5000/github